### ISSUE TITLE
japanc.map not present

### ISSUE THREAD

**Issue by drzel** [mickkn/projectq1q3#1]
I've got a copy of japanc_beta8.bsp on my server `sydney.fortressone.org`, we're planning on playing on it tomorrow to see if it's suitable for inclusion in the QWTF Oceania tournament.

I was hoping the .map file would be available but sadly no?

If you're interested come to our discord: https://discord.fortressone.org

We'll be recording mvds as well and I can post here for any issues we have. Excited about this map.

**Comment by mickkn** [comment]
Added
